[mcp_servers.heroui-pro]
url = "https://mcp.heroui.pro/mcp"
env_http_headers = { "x-heroui-personal-token" = "HEROUI_PERSONAL_TOKEN" }

[mcp_servers.heroui-react]
command = "pnx"
args = ["-y", "@heroui/react-mcp@latest"]

[features]
