/**
 * Centralized error IDs for tracking and logging errors across the application.
 * Used with the logger utility to ensure consistent error tracking in Sentry.
 */
export const ERROR_IDS = {
  // Post Management Errors
  POST_FETCH_FAILED: "POST_FETCH_FAILED",
  POST_CREATE_FAILED: "POST_CREATE_FAILED",
  POST_UPDATE_FAILED: "POST_UPDATE_FAILED",
  POST_DELETE_FAILED: "POST_DELETE_FAILED",
  POST_DUPLICATE_SLUG: "POST_DUPLICATE_SLUG",
  POST_BULK_DELETE_FAILED: "POST_BULK_DELETE_FAILED",
  POST_BULK_DELETE_PARTIAL_FAILURE: "POST_BULK_DELETE_PARTIAL_FAILURE",
  POST_BULK_PUBLISH_FAILED: "POST_BULK_PUBLISH_FAILED",
  POST_BULK_PUBLISH_PARTIAL_FAILURE: "POST_BULK_PUBLISH_PARTIAL_FAILURE",

  // Series Management Errors
  SERIES_FETCH_FAILED: "SERIES_FETCH_FAILED",
  SERIES_CREATE_FAILED: "SERIES_CREATE_FAILED",
  SERIES_UPDATE_FAILED: "SERIES_UPDATE_FAILED",
  SERIES_DELETE_FAILED: "SERIES_DELETE_FAILED",
  SERIES_DUPLICATE_SLUG: "SERIES_DUPLICATE_SLUG",
  SERIES_REORDER_FAILED: "SERIES_REORDER_FAILED",

  // Metadata Generation Errors
  METADATA_GENERATION_FAILED: "METADATA_GENERATION_FAILED",

  // Authentication Errors
  AUTH_SESSION_FAILED: "AUTH_SESSION_FAILED",
  AUTH_MIDDLEWARE_ERROR: "AUTH_MIDDLEWARE_ERROR",
  AUTH_POST_FAILED: "AUTH_POST_FAILED",
  AUTH_GET_FAILED: "AUTH_GET_FAILED",
  OAUTH_GOOGLE_FAILED: "OAUTH_GOOGLE_FAILED",

  // Database Errors
  DB_CONNECTION_FAILED: "DB_CONNECTION_FAILED",
  DB_HEALTH_CHECK_FAILED: "DB_HEALTH_CHECK_FAILED",

  // Cache Errors
  CACHE_READ_FAILED: "CACHE_READ_FAILED",
  CACHE_WRITE_FAILED: "CACHE_WRITE_FAILED",
  CACHE_DELETE_FAILED: "CACHE_DELETE_FAILED",
  CACHE_CONNECTION_FAILED: "CACHE_CONNECTION_FAILED",

  // Validation Errors
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
  INVALID_JSON: "INVALID_JSON",
  INVALID_PARAMS: "INVALID_PARAMS",
  POST_INVALID_JSON: "POST_INVALID_JSON",

  // Environment/Configuration Errors
  ENV_VALIDATION_FAILED: "ENV_VALIDATION_FAILED",

  // Asset Errors
  IMAGE_LOAD_FAILED: "IMAGE_LOAD_FAILED",

  // Media Errors
  MEDIA_FETCH_FAILED: "MEDIA_FETCH_FAILED",
  MEDIA_CREATE_FAILED: "MEDIA_CREATE_FAILED",
  MEDIA_UPDATE_FAILED: "MEDIA_UPDATE_FAILED",
  MEDIA_DELETE_FAILED: "MEDIA_DELETE_FAILED",
  MEDIA_LIST_FAILED: "MEDIA_LIST_FAILED",
  MEDIA_CONFIRM_FAILED: "MEDIA_CONFIRM_FAILED",
  UPLOAD_REQUEST_FAILED: "UPLOAD_REQUEST_FAILED",

  // R2 Storage Errors
  R2_PRESIGN_FAILED: "R2_PRESIGN_FAILED",
  R2_UPLOAD_FAILED: "R2_UPLOAD_FAILED",
  R2_DELETE_FAILED: "R2_DELETE_FAILED",
  R2_COPY_FAILED: "R2_COPY_FAILED",
  R2_HEAD_FAILED: "R2_HEAD_FAILED",

  // Temp Media Errors
  TEMP_MEDIA_SAVE_FAILED: "TEMP_MEDIA_SAVE_FAILED",
  TEMP_MEDIA_FETCH_FAILED: "TEMP_MEDIA_FETCH_FAILED",
  TEMP_MEDIA_DELETE_FAILED: "TEMP_MEDIA_DELETE_FAILED",
  MEDIA_PROMOTE_FAILED: "MEDIA_PROMOTE_FAILED",
} as const;

export type ErrorId = (typeof ERROR_IDS)[keyof typeof ERROR_IDS];
