name: SST workflow
#on:
#  push:
#    branches:
#      - '*'
#    tags-ignore:
#      - '*'
on:
  push:
    branches-ignore:
      - '*'
    tags-ignore:
      - '*'

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployPreviewEnv:
    runs-on: ubuntu-latest
    environment: preview
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ vars.NEXT_PUBLIC_GOOGLE_ANALYTICS }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ap-southeast-1
      - name: Deploy app
        run: |
          bun install
          bun run prisma generate && bun run prisma migrate deploy
          bunx sst deploy --stage preview
