name: SST workflow
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployProdEnv:
    runs-on: ubuntu-latest
    environment: Production
    env:
      NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ vars.NEXT_PUBLIC_GOOGLE_ANALYTICS }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ap-southeast-1
      - name: Deploy app
        run: |
          bun i
          bun prisma generate && bun prisma migrate deploy
          bun sst deploy --stage prod
