name: SST workflow
on: push

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployApp:
    runs-on: ubuntu-latest
    env:
     DATABASE_URL: ${{ secrets.DATABASE_URL }}
     NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ vars.NEXT_PUBLIC_GOOGLE_ANALYTICS }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ap-southeast-1
      - name: Deploy app
        run: |
          bun i && bun run prisma:generate && bunx sst deploy --stage prod
